---

name: Build all 

on:
  - push
  - pull_request

jobs:
  build_linux:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ 'ubuntu-18.04' ]
        go: [ '1.12', '1.13', '1.14' ]
        dir: ['basics', 'filehandling', 'web', 'misc', 'gotchas']
    
    name: ${{ matrix.dir }} with Go ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: build ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: |
          go fmt
          go get -d ./...
          go vet
          go build
